//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMB0001v4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMB0001v4.Resources.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string btn_quest_no {
            get {
                return ResourceManager.GetString("btn_quest_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string btn_quest_yes {
            get {
                return ResourceManager.GetString("btn_quest_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you?.
        /// </summary>
        public static string request_quest_whereareyou {
            get {
                return ResourceManager.GetString("request_quest_whereareyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you?.
        /// </summary>
        public static string request_quest_whoareyou {
            get {
                return ResourceManager.GetString("request_quest_whoareyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good to know...
        /// </summary>
        public static string response_after_good {
            get {
                return ResourceManager.GetString("response_after_good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t get that.. so?.
        /// </summary>
        public static string response_after_ididnt {
            get {
                return ResourceManager.GetString("response_after_ididnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answer is not an answer in that case...
        /// </summary>
        public static string response_after_noanswer {
            get {
                return ResourceManager.GetString("response_after_noanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no question asked..
        /// </summary>
        public static string response_after_noquestion {
            get {
                return ResourceManager.GetString("response_after_noquestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye..
        /// </summary>
        public static string response_bye_goodbye {
            get {
                return ResourceManager.GetString("response_bye_goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve already said goodbye...
        /// </summary>
        public static string response_bye_weve {
            get {
                return ResourceManager.GetString("response_bye_weve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello You...
        /// </summary>
        public static string response_greet_hello {
            get {
                return ResourceManager.GetString("response_greet_hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        public static string response_greet_hi {
            get {
                return ResourceManager.GetString("response_greet_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve already greet before...
        /// </summary>
        public static string response_greet_weve {
            get {
                return ResourceManager.GetString("response_greet_weve", resourceCulture);
            }
        }
    }
}
